config/routes.rb
Rails.application.routes.draw do
  resources :team_memberships
  resources :team_memberships
  resources :teams
  resources :employees

  root 'employees#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :subordinates, class_name: "Employee", foreign_key: "manager_id"
  belongs_to :manager, class_name: "Employee"

  has_many :team_memberships
  has_many :teams, through: :team_memberships

  has_one :managed_team, foreign_key: "manager_id", class_name: "Team"
end

app/models/team.rb
class Team < ActiveRecord::Base
  #self join within teams
  has_many :team_memberships
  has_many :employees, through: :team_memberships

  #across users
  belongs_to :manager, class_name: "Employee"
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
  belongs_to :employee
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :manager_id, :team_id)
    end
end

app/controllers/team_memberships_controller.rb
class TeamMembershipsController < ApplicationController
  before_action :set_team_membership, only: [:show, :edit, :update, :destroy]

  # GET /team_memberships
  # GET /team_memberships.json
  def index
    @team_memberships = TeamMembership.all
  end

  # GET /team_memberships/1
  # GET /team_memberships/1.json
  def show
  end

  # GET /team_memberships/new
  def new
    @team_membership = TeamMembership.new
  end

  # GET /team_memberships/1/edit
  def edit
  end

  # POST /team_memberships
  # POST /team_memberships.json
  def create
    @team_membership = TeamMembership.new(team_membership_params)

    respond_to do |format|
      if @team_membership.save
        format.html { redirect_to @team_membership, notice: 'Team membership was successfully created.' }
        format.json { render :show, status: :created, location: @team_membership }
      else
        format.html { render :new }
        format.json { render json: @team_membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_memberships/1
  # PATCH/PUT /team_memberships/1.json
  def update
    respond_to do |format|
      if @team_membership.update(team_membership_params)
        format.html { redirect_to @team_membership, notice: 'Team membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_membership }
      else
        format.html { render :edit }
        format.json { render json: @team_membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_memberships/1
  # DELETE /team_memberships/1.json
  def destroy
    @team_membership.destroy
    respond_to do |format|
      format.html { redirect_to team_memberships_url, notice: 'Team membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_membership
      @team_membership = TeamMembership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_membership_params
      params.require(:team_membership).permit(:employee_id, :team_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:team_name, :manager_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/team_memberships_helper.rb
module TeamMembershipsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.collection_select(:manager_id, Employee.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Manager</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <% if employee.manager.present? %>
          <td><%= employee.manager.name %><td>
        <% else %>
          <td>I am the boss or i dont have one</td>
        <% end %>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>
<% if @employee.manager.present? %>
<p>
  <strong>Managed by:</strong>
  <%= @employee.manager.name %>
</p>
<% end %>

<h3><%= @employee.name %> Teams</h3>

<% @employee.teams.each do |team| %>
  <ul>
    <li><%= team.team_name %></li>
  </ul>
<% end %>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SelfJoin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/team_memberships/_form.html.erb
<%= form_for(@team_membership) do |f| %>
  <% if @team_membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_membership.errors.count, "error") %> prohibited this team_membership from being saved:</h2>

      <ul>
      <% @team_membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
     <%= f.select :employee_id, Employee.all.collect { |q| [ q.name, q.id ] } %>
  </div>
  <div class="field">
     <%= f.select :team_id, Team.all.collect { |t| [ t.team_name, t.id ] } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_memberships/edit.html.erb
<h1>Editing Team Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_membership %> |
<%= link_to 'Back', team_memberships_path %>

app/views/team_memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Team Memberships</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_memberships.each do |team_membership| %>
      <tr>
        <td><%= team_membership.employee.name %></td>
        <td><%= team_membership.team.team_name %></td>
        <td><%= link_to 'Show', team_membership %></td>
        <td><%= link_to 'Edit', edit_team_membership_path(team_membership) %></td>
        <td><%= link_to 'Destroy', team_membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team membership', new_team_membership_path %>

app/views/team_memberships/new.html.erb
<h1>New Team Membership</h1>

<%= render 'form' %>

<%= link_to 'Back', team_memberships_path %>

app/views/team_memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @team_membership.employee.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @team_membership.team.team_name %>
</p>


<%= link_to 'Edit', edit_team_membership_path(@team_membership) %> |
<%= link_to 'Back', team_memberships_path %>